//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarineFuelMonitor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class UserSetings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserSetings defaultInstance = ((UserSetings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserSetings())));
        
        public static UserSetings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=rm-uf64fql0n27338879o.mysql.rds.aliyuncs.com;uid=tuser;pwd=t_user001;Datab" +
            "ase=shipinfo;CharSet=utf8;port=3306")]
        public string RDSConnString {
            get {
                return ((string)(this["RDSConnString"]));
            }
            set {
                this["RDSConnString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.163.163")]
        public string PLCConnIp {
            get {
                return ((string)(this["PLCConnIp"]));
            }
            set {
                this["PLCConnIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string GPSPort {
            get {
                return ((string)(this["GPSPort"]));
            }
            set {
                this["GPSPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string DeleteDay {
            get {
                return ((string)(this["DeleteDay"]));
            }
            set {
                this["DeleteDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13952850491,18652863099")]
        public string ManagerTel {
            get {
                return ((string)(this["ManagerTel"]));
            }
            set {
                this["ManagerTel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("船名")]
        public string MarineName {
            get {
                return ((string)(this["MarineName"]));
            }
            set {
                this["MarineName"] = value;
            }
        }
    }
}
